# Generated by Django 4.0.4 on 2022-06-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='login',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='surname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
