# Generated by Django 4.0.4 on 2022-06-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userdata_email_userdata_login_userdata_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='password',
        ),
    ]
