# Generated by Django 4.0.4 on 2022-06-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
